---
title: Code of Conduct
toc-depth: 1
---

The SCDNEY community values
an open approach to science that promotes 

* sharing of ideas, code, software and expertise
* collaboration
* diversity and inclusivity
* a kind and welcoming environment
* community contributions

In line with these values, SCDNEY is dedicated to providing a welcoming, supportive, collegial experience free of harassment, intimidation, and bullying regardless of:

* identity: gender, gender identity and expression, sexual orientation, disability, physical appearance, ethnicity, body size, race, age, religion, language, etc.
* intellectual position: approaches to data analysis, software preferences, coding style, scientific perspective, stage of career, etc.

By participating in this community, you agree not to engage in behavior contrary to these values at any SCDNEY-sponsored event (in person or virtual, including but not limited to talks, workshops, poster sessions, social activities), electronic communication channels, or packages (including commits).

We do not tolerate harassment, intimidation, or bullying of community members. Sexual language and imagery are not appropriate in presentations, communications or in online venues, including chats.

Any person/s violating the Code of Conduct may be sanctioned or expelled temporarily or permanently from an electronic platform or event at the discretion of the Code of Conduct committee.

#### _Examples of unacceptable harassment, intimidation, and bullying behavior_

Harassment includes, but is not limited to:

* Making comments in chats, to an audience or personally, that belittle or demean another person
* Sharing sexual images online
* Harassing photography or recording
* Sustained disruption of talks or other events
* Unwelcome sexual attention
* Advocating for, or encouraging, any of the above behavior

Intimidation and bullying include, but are not limited to:

* Aggressive or browbeating behavior 
* Mocking or insulting another person’s intellect, work, perspective, or question/comment
* Making reference to someone’s gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, religion, or other personal attributes in the context of a scientific discussion
* Deliberately making someone feel unwelcome
* Trolling behaviour (deliberately inflammatory or offensive messages)
* Sustained off-topic posts

## Enforcement
Anyone asked to stop harassing or intimidating behavior are expected to comply immediately.

If a person contravene the Code of Conduct, the Code of Conduct committee retains the right to take any action that ensures a welcoming environment for all community members. This includes warning the alleged offender or temporary/permanent expulsion from the event and/or electronic platforms under SCDNEY’s control.

The Code of Conduct committee may take action to redress anything designed to, or with the clear impact of, disrupting an event or electronic communication platform or making the environment hostile for any community member.

We expect everyone in the SCDNEY community to comply with the Code of Conduct when participating in SCDNEY events and online communication platforms.

## Reporting
If someone makes you or anyone else feel unsafe or unwelcome, please report it as soon as possible. You can make a report either anonymously or personally. All reports will be reviewed by the Code of Conduct Committee and will be kept confidential.

#### _Electronically_

You can email the Code of Conduct Committee (maths.bioconductor@sydney.edu.au). Please include screenshots/copies of all relevant electronic conversations whenever possible (you don’t need to compromise your anonymity!).

#### _Personal Report (for any SCDNEY events: in-person or virtual)_

You can make a personal report to any member of the event Code of Conduct committee present at an event. 

When taking a personal report, we will ensure you are safe and cannot be overheard. We may involve other event staff to ensure your report is managed properly. Once safe, we’ll ask you to tell us about what happened. This can be upsetting, but we’ll handle it as respectfully as possible, and you can bring someone to support you. You won’t be asked to confront anyone, and we won’t tell anyone who you are.

Our team will be happy to help you get the relevant support (e.g. help contacting hotel/venue security, local law enforcement, local support services, provide escorts, or otherwise assist you to feel safe for the duration of the event).

We value your attendance and participation at SCDNEY events and in our community.

(Adapted from the [BioC 2020 Code of Conduct][1])

[1]: https://bioc2020.bioconductor.org/code_of_conduct
