---
title: Contribute to SCDNEY
---

SCDNEY would not be possible without the contributions of the R community. No matter your current skills, it's possible to contribute back to SCDNEY. 

## File issues {#issues}

If you've found a bug in any of the packages, first create a minimal [reprex](https://www.tidyverse.org/help#reprex). Spend some time trying to make it as minimal as possible: the more time you spend doing this, the easier it will be for the tidyverse team to fix it. Then file it on the GitHub repo of the appropriate package.


## Contribute code

If you are a more experienced programmer, you might want to help out with the package development. Before you do a pull request, you should always file an issue and make sure someone from the SCDNEY team agrees that it's a problem, and is happy with your basic proposal for fixing it. We don't want you to spend a bunch of time on something that we don't think is a good idea.

Make sure to read the [tidyverse style guide](https://style.tidyverse.org/) to ensure that your new code and documentation matches the existing style, and our [code review principles](https://code-review.tidyverse.org/) for advice on how to submit a great pull request. Using these guides makes the overall review process much smoother!